name: Current Date Demo

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "the release version of the build"
        type: string
        default: ''
        required: false # Not required if none will use curDate

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        if: inputs.releaseVersion == ''
        id: date1
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          # format: "YYYY-MM-DD"
          format: "YYYY_MM_DDTHH_mm_ss_SSS"

      - name: Test
        run: |
          echo "${{ inputs.releaseVersion || steps.date1.outputs.time }}"